export const uiText = {
  title: "Blindfold",
  subtitle: "Uma venda. Nenhuma saída visível.",
  narratorLabel: "Narrador",
  playerLabel: "Você",
  currentActionLabel: "Ação",
  historyTitle: "Sessão",
  historyCollapseLabel: "Fechar sessão",
  historyExpandLabel: "Abrir sessão",
  sidebarActionsLabel: "Controlos da sessão",
  mainAriaLabel: "Blindfold",
  historyAriaLabel: "Histórico de sessão",
  inputAriaLabel: "A tua ação",
  inputPlaceholder: "Escreve o teu caminho...",
  submitLabel: "Enviar",
  themeLightLabel: "Modo claro",
  themeDarkLabel: "Modo escuro",
  audioOnLabel: "Silenciar",
  audioOffLabel: "Ambiente",
  requestError: "O narrador ficou em silêncio.",
  connectionError: "A ligação falhou. Só ouves a tua respiração."
};
